
TEAM_NEWS_SOURCES = {
    "Alaves": [
        "https://www.noticiasdealava.eus/alaves",
        "https://www.eitb.eus/es/deportes/futbol/alaves",
        "https://www.eldesmarque.com/futbol/deportivo-alaves/",
        "https://www.mundodeportivo.com/futbol/alaves",
        "https://www.relevo.com/futbol/equipos/deportivo-alaves",
        "https://as.com/noticias/deportivo-alaves",
        "https://www.marca.com/futbol/alaves.html?intcmp=MENUESCU&s_kw=alaves",
    ],
    "Athletic Bilbao": [
        "https://www.deia.eus/athletic/",
        "https://www.eitb.eus/es/deportes/futbol/athletic/",
        "https://www.marca.com/futbol/athletic.html?intcmp=MENUESCU&s_kw=athletic",
        "https://as.com/noticias/athletic/",
        "https://www.estadiodeportivo.com/futbol/athletic-club-bilbao/",
        "https://www.eldesmarque.com/futbol/athletic-club/",
    ],
    "Atletico Madrid": [
        "https://www.soycolchonero.es",
        "https://atletimania.com",
        "https://estoesatleti.es",
        "https://www.marca.com/futbol/atletico.html?intcmp=MENUESCU&s_kw=atletico",
        "https://as.com/noticias/atletico-madrid/",
        "https://www.estadiodeportivo.com/futbol/atletico-madrid/",
        "https://www.eldesmarque.com/futbol/atletico-de-madrid/",
    ],
    "Barcelona": [
        "https://www.sport.es/es/barca/",
        "https://www.mundodeportivo.com/futbol/fc-barcelona",
        "https://www.fcbarcelonanoticias.com",
        "https://www.marca.com/futbol/barcelona.html?intcmp=MENUESCU&s_kw=barcelona",
        "https://as.com/noticias/fc-barcelona/",
        "https://www.estadiodeportivo.com/futbol/barcelona/",
        "https://www.eldesmarque.com/futbol/fc-barcelona/",
    ],
    "Betis": [
        "https://www.estadiodeportivo.com/futbol/betis/",
        "https://www.eldesmarque.com/futbol/real-betis/",
        "https://www.marca.com/futbol/betis.html?intcmp=MENUESCU&s_kw=betis",
        "https://as.com/noticias/real-betis/?omnil=mod_esc",
        "https://mundobetis.com",
    ],
    "Celta de Vigo": [
        "https://www.farodevigo.es/celta-de-vigo/",
        "https://www.lavozdegalicia.es/gradario/",
        "https://www.estadiodeportivo.com/futbol/celta/",
        "https://www.eldesmarque.com/futbol/celta-de-vigo/",
        "https://as.com/noticias/real-club-celta-de-vigo/?omnil=mod_esc",
        "https://www.marca.com/futbol/celta.html?intcmp=MENUESCU&s_kw=celta",
    ],
    "Elche": [
        "https://www.marca.com/futbol/elche.html?intcmp=MENUESCU&s_kw=elche",
        "https://as.com/noticias/elche-cf/",
        "https://diariofranjiverde.com/category/elchecf/",
        "https://teleelx.es/category/deportes/elche-cf/",
        "https://alicanteplaza.es/tag/elche-cf",
        "https://www.estadiodeportivo.com/futbol/elche/",
        "https://www.eldesmarque.com/futbol/elche-cf/",
    ],
    "Espanyol": [
        "https://www.marca.com/futbol/espanyol.html?intcmp=MENUESCU&s_kw=espanyol",
        "https://as.com/noticias/rcd-espanyol/",
        "https://www.eldesmarque.com/futbol/rcd-espanyol/",
        "https://www.estadiodeportivo.com/futbol/espanyol/",
        "https://www.mundodeportivo.com/futbol/rcd-espanyol",
        "https://www.sport.es/es/espanyol/",
        "https://www.lagradaonline.com",
        "https://el1900.com"
    ],
    "Getafe": [
        "https://www.marca.com/futbol/getafe.html?intcmp=MENUESCU&s_kw=getafe",
        "https://as.com/noticias/getafe-cf/",
        "https://www.eldesmarque.com/futbol/getafe-cf/",
        "https://www.estadiodeportivo.com/futbol/getafe/",
    ],
    "Girona": [
        "https://www.marca.com/futbol/girona.html?intcmp=MENUESCU&s_kw=girona",
        "https://as.com/noticias/girona-cf/",
        "https://www.eldesmarque.com/futbol/girona-fc/",
        "https://www.estadiodeportivo.com/futbol/girona/",
        "https://www.lesportiudecatalunya.cat/girona.html",
    ],
    "Levante": [
        "https://www.superdeporte.es/levante-ud/",
        "https://plazadeportiva.valenciaplaza.com/levanteud/",
        "https://www.levante-emv.com/levante-ud/",
        "https://www.lasprovincias.es/levanteud/",
        "https://www.marca.com/futbol/levante.html?intcmp=MENUESCU&s_kw=levante",
        "https://as.com/noticias/levante-ud/",
        "https://www.estadiodeportivo.com/futbol/levante/",
        "https://www.eldesmarque.com/futbol/levante-ud/",
    ],
    "Mallorca": [
        "https://www.ultimahora.es/deportes/real-mallorca.html",
        "https://www.diariodemallorca.es/rcd-mallorca/",
        "https://www.futboldesdemallorca.com",
        "https://www.marca.com/futbol/mallorca.html",
        "https://as.com/noticias/real-mallorca/",
        "https://www.estadiodeportivo.com/futbol/mallorca/",
        "https://www.eldesmarque.com/futbol/rcd-mallorca/",
    ],
    "Osasuna": [
        "https://www.eitb.eus/es/deportes/futbol/osasuna/",
        "https://www.diariodenavarra.es/noticias/deportes/futbol/osasuna/portada/",
        "https://www.noticiasdenavarra.com/osasuna/",
        "https://www.navarratelevision.es/seccion/osasuna",
        "https://as.com/noticias/osasuna/",
        "https://www.marca.com/futbol/osasuna.html?intcmp=MENUESCU&s_kw=osasuna",
        "https://www.estadiodeportivo.com/futbol/osasuna/",
        "https://www.eldesmarque.com/futbol/osasuna/",
    ],
    "Oviedo": [
        "https://www.elcomercio.es/real-oviedo/?ref=https%3A%2F%2Fwww.elcomercio.es%2Freal-oviedo%2F",
        "https://www.lavozdeasturias.es/temas/real-oviedo",
        "https://as.com/noticias/real-oviedo/",
        "https://www.marca.com/futbol/oviedo.html",
        "https://www.estadiodeportivo.com/futbol/oviedo/",
        "https://www.eldesmarque.com/futbol/real-oviedo/",
    ],
    "Rayo Vallecano": [
        "https://www.marca.com/futbol/rayo.html?intcmp=MENUESCU&s_kw=rayo",
        "https://as.com/noticias/rayo-vallecano/",
        "https://www.eldesmarque.com/futbol/rayo-vallecano/",
        "https://www.estadiodeportivo.com/futbol/rayo-vallecano/",
        "https://unionrayo.com",
    ],
    "Real Madrid": [
        "https://www.marca.com/futbol/real-madrid.html?intcmp=MENUESCU&s_kw=realmadrid",
        "https://as.com/noticias/real-madrid/?omnil=mod_esc",
        "https://www.bernabeudigital.com",
        "https://realmadridconfidencial.com",
        "https://okdiario.com/diariomadridista/real-madrid/1/",
        "https://www.estadiodeportivo.com/futbol/real-madrid/",
        "https://www.eldesmarque.com/futbol/real-madrid/",
    ],
    "Real Sociedad": [
        "https://www.diariovasco.com/real-sociedad/",
        "https://www.eitb.eus/es/deportes/futbol/real-sociedad/",
        "https://www.marca.com/futbol/real-sociedad.html?intcmp=MENUESCU&s_kw=realsociedad",
        "https://as.com/noticias/real-sociedad/",
        "https://www.estadiodeportivo.com/futbol/real-sociedad/",
        "https://www.eldesmarque.com/futbol/real-sociedad/"
    ],
    "Sevilla FC": [
        "https://orgullobiri.com",
        "https://www.vamosmisevillafc.com",
        "https://www.estadiodeportivo.com/futbol/sevilla-fc/",
        "https://www.eldesmarque.com/futbol/sevilla-fc/",
        "https://www.marca.com/futbol/sevilla.html?intcmp=MENUESCU&s_kw=sevilla",
        "https://as.com/noticias/sevilla-futbol-club/?omnil=mod_esc",
    ],
    "Valencia": [
        "https://www.superdeporte.es/valencia-cf/",
        "https://plazadeportiva.valenciaplaza.com/valenciacf/",
        "https://www.levante-emv.com/valencia-cf/",
        "https://www.lasprovincias.es/valenciacf/",
        "https://www.marca.com/futbol/valencia.html?intcmp=MENUESCU&s_kw=valencia,"
        "https://as.com/noticias/valencia-cf/?omnil=mod_esc",
        "https://www.estadiodeportivo.com/futbol/valencia/",
        "https://www.eldesmarque.com/futbol/valencia-cf/",
    ],
    "Villareal": [
        "https://www.marca.com/futbol/villarreal.html?intcmp=MENUESCU&s_kw=villarreal",
        "https://as.com/noticias/villarreal-cf/",
        "https://www.estadiodeportivo.com/futbol/villarreal/",
        "https://www.eldesmarque.com/futbol/villarreal-cf/",
        "https://www.elperiodicomediterraneo.com/villarrealcf/",
        
    ],
}
