-- Active Supabase schema reference for the Biwenger-only extraction pipeline.
-- Article/news tables are intentionally excluded from the active schema.

create extension if not exists "pgcrypto";

create table if not exists public.biwenger_current_team (
    id bigint generated by default as identity primary key,
    name text not null,
    points integer not null,
    market_value integer not null,
    mv_change_eur integer not null,
    status text not null,
    games_played integer not null,
    average_points double precision not null,
    "form_t-1" integer not null,
    "form_t-2" integer not null,
    "form_t-3" integer not null,
    "form_t-4" integer not null,
    "form_t-5" integer not null,
    created_at timestamptz default now()
);

create table if not exists public.biwenger_player_stats (
    id bigint generated by default as identity primary key,
    player_name text not null,
    team text not null,
    position text,
    status text,
    status_detail text,
    points integer not null default 0,
    value bigint not null default 0,
    min_value bigint not null default 0,
    max_value bigint not null default 0,
    matches_played integer not null default 0,
    average double precision not null default 0,
    market_purchases_pct double precision not null default 0,
    market_sales_pct double precision not null default 0,
    market_usage_pct double precision not null default 0,
    season text,
    as_of_date date not null,
    created_at timestamptz default now()
);

create table if not exists public.biwenger_player_matches (
    id bigint generated by default as identity primary key,
    player_name text not null,
    team text not null,
    season_label text,
    round_label text,
    match_date date,
    points integer,
    best_xi boolean,
    events jsonb,
    as_of_date date not null,
    created_at timestamptz default now()
);

create table if not exists public.biwenger_player_value (
    id bigint generated by default as identity primary key,
    slug text not null,
    player_name text,
    team text,
    date date not null,
    market_value_eur bigint not null,
    created_at timestamptz default now(),
    unique (slug, date)
);
