[biwenger]
biwenger_email = "your-main-biwenger-email@example.com"
biwenger_password = "replace-with-your-main-biwenger-password"

[biwenger_player_scraper]
biwenger_email = "your-player-scraper-email@example.com"
biwenger_password = "replace-with-your-player-scraper-password"
